version: "3.8"

services:
  certbot:
    container_name: certbot
    image: camelstrike/certbot-doth:$TAG
    build:
      context: ./certbot
      args:
        - CERTBOT_TAG
        - CERTBOT_DOMAIN
        - CLOUDFLARE_TOKEN
        - CERTBOT_EMAIL
        - CERTBOT_ENV
    networks:
      pihole-doth:
        ipv4_address: 172.30.30.40
    volumes:
      - certbot:/etc/letsencrypt
    depends_on:
      - nginx
      - unbound
      - pihole
  pihole:
    container_name: pihole
    image: camelstrike/pihole-doth:$TAG
    build:
      context: ./pihole
      args:
        - PIHOLE_TAG
    ports:
      - 8080:80/tcp
    networks:
      pihole-doth:
        ipv4_address: 172.30.30.30
    environment:
      TZ: 'UTC'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
      # Unbound fixed IP
      PIHOLE_DNS_: '172.30.30.10#5335'
      DNSSEC: 'true'
      WEBTHEME: 'default-dark'
    volumes:
      - pihole:/etc/pihole/
      - pihole-dnsmask:/etc/dnsmasq.d/
      - pihole-updatelists:/etc/pihole-updatelists/
      - ./pihole/pihole-updatelists.conf:/etc/pihole-updatelists/pihole-updatelists.conf
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - unbound
  nginx:
    container_name: nginx
    image: camelstrike/nginx-doth:$TAG
    build:
      context: ./nginx
      args:
        - TAG
        - NGINX_TAG
        - CERTBOT_DOMAIN
    ports:
     - 53:53/tcp
     - 53:53/udp
     - 853:853/tcp
     - 443:443/tcp
     - 80:80/tcp
    networks:
      pihole-doth:
        ipv4_address: 172.30.30.20
    volumes:
      - certbot:/etc/letsencrypt
    depends_on:
      - unbound
  unbound:
    container_name: unbound
    image: camelstrike/unbound-doth:$TAG
    build:
      context: ./unbound
      args:
        - UNBOUND_TAG
    networks:
      pihole-doth:
        ipv4_address: 172.30.30.10

volumes:
  pihole:
  pihole-dnsmask:
  pihole-updatelists:
  certbot:

networks:
  pihole-doth:
    ipam:
      driver: default
      config:
        - subnet: "172.30.30.0/24"
