version: "3.8"

services:
  certbot:
    container_name: certbot
    image: camelstrike/certbot-doth:$TAG
    build:
      context: ./certbot
      args:
        - CERTBOT_TAG
        - CERTBOT_DOMAIN
        - CLOUDFLARE_TOKEN
        - CERTBOT_EMAIL
        - CERTBOT_ENV
    networks:
      - pihole-doth
    volumes:
      - certbot:/etc/letsencrypt
    depends_on:
      - nginx
  pihole:
    container_name: pihole
    image: camelstrike/pihole-doth:$TAG
    build:
      context: ./pihole
      args:
        - PIHOLE_TAG
    ports:
      - 8080:80/tcp
    networks:
      - pihole-doth
    environment:
      TZ: 'UTC'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
      # quad9 Secured: Malware blocking, DNSSEC Validation
      PIHOLE_DNS_: '9.9.9.9;149.112.112.112'
      DNSSEC: 'true'
      WEBTHEME: 'default-dark'
    volumes:
      - pihole:/etc/pihole/
      - pihole-dnsmask:/etc/dnsmasq.d/
      - pihole-updatelists:/etc/pihole-updatelists/
      - ./pihole/pihole-updatelists.conf:/etc/pihole-updatelists/pihole-updatelists.conf
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: camelstrike/nginx-doth:$TAG
    build:
      context: ./nginx
      args:
        - TAG
        - NGINX_TAG
        - CERTBOT_DOMAIN
    ports:
     - 53:53/tcp
     - 53:53/udp
     - 853:853/tcp
     - 443:443/tcp
     - 80:80/tcp
    networks:
      - pihole-doth
    volumes:
      - certbot:/etc/letsencrypt

networks:
  pihole-doth:

volumes:
  pihole:
  pihole-dnsmask:
  pihole-updatelists:
  certbot:
