version: "3.8"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:$PIHOLE_TAG
    build:
      context: ./pihole
      dockerfile: Dockerfile
      args:
        - PIHOLE_TAG=${PIHOLE_TAG}
    ports:
      - "153:53/tcp"
      - "153:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'UTC'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'
      # quad9 Secured: Malware blocking, DNSSEC Validation
      PIHOLE_DNS_: '9.9.9.9;149.112.112.112'
      DNSSEC: 'true'
      WEBTHEME: 'default-dark'
    env_file:
      - .env
    volumes:
      - pihole:/etc/pihole/
      - pihole-dnsmask:/etc/dnsmasq.d/
      - pihole-updatelists:/etc/pihole-updatelists/
      - ./pihole/pihole-updatelists.conf:/etc/pihole-updatelists/pihole-updatelists.conf
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx:$NGINX_TAG
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - NGINX_TAG=${NGINX_TAG}
    env_file:
      - .env


volumes:
  pihole:
  pihole-dnsmask:
  pihole-updatelists:
  certbot:
