version: "3.8"

services:
  certbot:
    container_name: certbot
    image: camelstrike/certbot-doth:$TAG
    environment:
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_ENV=${CERTBOT_ENV}
    env_file:
      - .env
    networks:
      pihole-doth:
        ipv4_address: 172.30.30.40
    volumes:
      - certbot:/etc/letsencrypt
    depends_on:
      - unbound
      - pihole
  pihole:
    container_name: pihole
    image: camelstrike/pihole-doth:$TAG
    env_file:
      - .env
    ports:
      - 8080:80/tcp
    dns:
      - 127.0.0.1
    networks:
      pihole-doth:
        ipv4_address: 172.30.30.30
    environment:
      TZ: 'UTC'
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD:-changeme}'
      # Unbound fixed IP
      PIHOLE_DNS_: '172.30.30.10#5335'
      DNSSEC: 'true'
      WEBTHEME: 'default-dark'
      # pihole-updatelists lists
      ADLISTS_URL: '${ADLISTS_URL}'
      WHITELIST_URL: '${WHITELIST_URL}'
      REGEX_WHITELIST_URL: '${REGEX_WHITELIST_URL}'
      BLACKLIST_URL: '${BLACKLIST_URL}'
      REGEX_BLACKLIST_URL: '${REGEX_BLACKLIST_URL}'
    volumes:
      - pihole:/etc/pihole/
      - pihole-dnsmask:/etc/dnsmasq.d/
      - pihole-updatelists:/etc/pihole-updatelists/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - unbound
  nginx:
    container_name: nginx
    image: camelstrike/nginx-doth:$TAG
    environment:
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
    env_file:
      - .env
    ports:
     - 53:53/tcp
     - 53:53/udp
     - 853:853/tcp
     - 443:443/tcp
     - 80:80/tcp
    networks:
      pihole-doth:
        ipv4_address: 172.30.30.20
    volumes:
      - certbot:/etc/letsencrypt
    depends_on:
      - certbot
      - unbound
  unbound:
    container_name: unbound
    image: camelstrike/unbound-doth:$TAG
    env_file:
      - .env
    networks:
      pihole-doth:
        ipv4_address: 172.30.30.10

volumes:
  pihole:
  pihole-dnsmask:
  pihole-updatelists:
  certbot:

networks:
  pihole-doth:
    ipam:
      driver: default
      config:
        - subnet: "172.30.30.0/24"
