version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-amd:
    machine:
      image: ubuntu-2004:2022.04.1
    resource_class: medium
    steps:
      - checkout
      - run: 
          command: |
            cd build
            export TAG=2.0
            export DOCKER_BUILDKIT=1
            docker-compose build
            docker login -u $DOCKER_USER -p $DOCKER_CIRCLECI_TOKEN
            docker-compose push
  build-arm:
    machine:
      image: ubuntu-2004:2022.04.1
    resource_class: arm.medium
    steps:
      - checkout
      - run: 
          command: |
            cd build
            export TAG=2.0
            export DOCKER_BUILDKIT=1
            docker-compose build
            docker login -u $DOCKER_USER -p $DOCKER_CIRCLECI_TOKEN
            docker-compose push

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-amd
      - build-arm
